name: CI_Dispatch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub dispatch event
      env: 
        MY_GITHUB_TOKEN: ${{ secrets.TOKEN0 }}
      run: |
        curl --request POST 'https://api.github.com/repos/nobuyuki83/delfem2-python-bindings/dispatches' \
        --header 'Authorization: Bearer ${{env.MY_GITHUB_TOKEN}}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "event_type": "updated-delfem2"
        }'
